# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
import numpy as np
arr=np.random.randint(1, 21,size=(5, 5))
print(arr)

arr[:, 2]=1
print(arr)


arr2=np.arange(1, 17).reshape(4, 4)
print(arr2)
np.fill_diagonal(arr2, 0)
print(arr2)


arr3=np.arange(1, 37).reshape((6, 6))
print(arr3)
print(arr3[2:5, 1:4])


arr4=np.random.randint(1, 21, size=(5, 5))
print(arr4)
bo=np.concatenate((arr4[0,:], arr4[-1,:] , arr4[1:-1,0], arr4[1:-1, -1]))
print(bo)


[[16 14  9 20 14]
 [ 4  3 18 17 12]
 [ 2 16  9  5  4]
 [20  1  2 11  6]
 [12  9  2  2 19]]
[[16 14  1 20 14]
 [ 4  3  1 17 12]
 [ 2 16  1  5  4]
 [20  1  1 11  6]
 [12  9  1  2 19]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[ 5 19  4 13  6]
 [ 9 11  9 15  1]
 [18 11 11  9 18]
 [14  6 15  1 19]
 [ 7 17 15 16 17]]
[ 5 19  4 13  6  7 17 15 16 17  9 18 14  1 18 19]


In [3]:
arr5=np.random.randint(1, 11, size=(3, 4))
arr6=np.random.randint(1, 11, size=(3, 4))
print(arr5)
print(arr6)
print(arr5+arr6)
print(arr5-arr6)
print(arr5*arr6)
print(arr5/arr6)

[[ 6  3  9  4]
 [ 9  6 10  5]
 [ 5  5  7 10]]
[[2 1 4 1]
 [7 5 2 5]
 [9 4 4 2]]
[[ 8  4 13  5]
 [16 11 12 10]
 [14  9 11 12]]
[[ 4  2  5  3]
 [ 2  1  8  0]
 [-4  1  3  8]]
[[12  3 36  4]
 [63 30 20 25]
 [45 20 28 20]]
[[3.         3.         2.25       4.        ]
 [1.28571429 1.2        5.         1.        ]
 [0.55555556 1.25       1.75       5.        ]]


In [4]:
arr7=np.arange(1, 17).reshape(4, 4)
print(arr7)
rs=np.sum(arr7, axis=1)
cl=np.sum(arr7, axis=0)
print(rs)
print(cl)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]
[28 32 36 40]


In [5]:
arr8=np.random.randint(1, 21, size=(5, 5))
print(arr8)
print(np.mean(arr8))
print(np.median(arr8))
print(np.std(arr8))
print(np.var(arr8))

[[ 2  1 10 13 11]
 [20 14  8  1  9]
 [18  8 17  3  3]
 [18 13  1  8 13]
 [18  6 14  2  1]]
9.28
9.0
6.21945335218458
38.68160000000001


In [6]:
arr9=np.arange(1, 10).reshape(3, 3)
print(arr9)
st=np.std(arr9)
m=np.mean(arr9)

n=(arr9-m)/st
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [7]:
arr10=np.random.randint(1, 11, size=(3,3))
row=np.random.randint(1, 11, size=(3,))
print(arr10)
print(row)
print(arr10+row)

[[10  1  7]
 [ 5  4  3]
 [ 6  6  1]]
[7 9 5]
[[17 10 12]
 [12 13  8]
 [13 15  6]]


In [8]:
arr11=np.random.randint(1, 17, size=(4, 4))
row=np.random.randint(1, 17, size=(4,))
print(arr11)
print(row)
print(arr11-row)

[[ 5  1  2  8]
 [ 8 15 15  8]
 [ 8  4  8  1]
 [ 8 14 11  3]]
[10 12 16  9]
[[ -5 -11 -14  -1]
 [ -2   3  -1  -1]
 [ -2  -8  -8  -8]
 [ -2   2  -5  -6]]


In [9]:
matrix=np.random.randint(1, 11, size=(3, 3))
print(matrix)
print(np.linalg.det(matrix))
print(np.linalg.eigvals(matrix))
print(np.linalg.inv(matrix))


[[7 2 7]
 [3 1 5]
 [6 7 3]]
-77.00000000000001
[14.26657103  1.20658315 -4.47315417]
[[ 0.41558442 -0.55844156 -0.03896104]
 [-0.27272727  0.27272727  0.18181818]
 [-0.19480519  0.48051948 -0.01298701]]


In [10]:
m1=np.random.randint(1, 11, size=(2, 3))
m2=np.random.randint(1, 11, size=(3, 2))
print(m1)
print(m2)
print(np.dot(m1, m2))


[[7 8 8]
 [9 3 9]]
[[1 8]
 [4 1]
 [4 7]]
[[ 71 120]
 [ 57 138]]


In [13]:
m3=np.arange(1,10).reshape(3,3)
print(m3)
r1=m3.reshape(9, 1)
print(r1)
r2=r1.reshape(1, 9)
print(r2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[1 2 3 4 5 6 7 8 9]]


In [16]:
m4=np.random.randint(1, 21, size=(5, 5))
print(m4)
f1=m4.flatten()
print(f1)
rp=f1.reshape(5, 5)
print(rp)

[[ 2 19  6  1  1]
 [ 1 20 18 17 20]
 [17  2  4  6 19]
 [ 8  7 20  5 20]
 [ 1  5  8 16  3]]
[ 2 19  6  1  1  1 20 18 17 20 17  2  4  6 19  8  7 20  5 20  1  5  8 16
  3]
[[ 2 19  6  1  1]
 [ 1 20 18 17 20]
 [17  2  4  6 19]
 [ 8  7 20  5 20]
 [ 1  5  8 16  3]]


In [17]:
m5=np.random.randint(1, 21, size=(4,4))
print(m5)
m5[m5>10]=10
print(m5)

[[15  2  4  9]
 [11  6  3  3]
 [ 9 13  4  3]
 [14 19 18  7]]
[[10  2  4  9]
 [10  6  3  3]
 [ 9 10  4  3]
 [10 10 10  7]]


In [20]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)
s=np.sort(data, order="age")
print(s)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [21]:
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)
distance=np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print(distance)

Original array:
[(1, 2) (3, 4) (5, 6)]
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [22]:
import numpy.ma as ma
arr=np.random.randint(1,21, size=(4,4 ))
masked_array = ma.masked_greater(arr, 10)
print("Original array:")
print(arr)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[13 20 13  9]
 [20 10  7 10]
 [17  4 11 15]
 [10 18 13  3]]
Masked array:
[[-- -- -- 9]
 [-- 10 7 10]
 [-- 4 -- --]
 [10 -- -- 3]]
Sum of unmasked elements: 53


In [23]:
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[12 19 11]
 [ 5  1  8]
 [ 2  8  1]]
Masked array:
[[-- 19 11]
 [5 -- 8]
 [2 8 --]]
Modified masked array:
[[ 8 19 11]
 [ 5  8  8]
 [ 2  8  8]]
